project_id = "myggeoklmdffbjrphprf"

[functions.evaluate-response]
verify_jwt = false

[functions.analyze-trends]
verify_jwt = false

[functions.extract-keypoints]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false